USE test_cs;
DROP TABLE IF EXISTS test_foreach;
CREATE TABLE test_foreach (name VARCHAR(64) CHARSET ascii);
CREATE DATABASE IF NOT EXISTS test_cs_foreach_00;
CREATE DATABASE IF NOT EXISTS test_cs_foreach_01;
CREATE DATABASE IF NOT EXISTS test_cs_foreach_02;
CREATE DATABASE IF NOT EXISTS test_cs_foreach_03;
