-- 
-- Number of row cardinality per keys per columns in InnoDB tables
-- 
CREATE OR REPLACE
ALGORITHM = MERGE
SQL SECURITY INVOKER
VIEW innodb_index_rows AS
  SELECT
    STATISTICS.TABLE_SCHEMA,
    STATISTICS.TABLE_NAME,
    STATISTICS.INDEX_NAME,
    STATISTICS.SEQ_IN_INDEX,
    STATISTICS.COLUMN_NAME,
    TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(rows_per_key, ',', SEQ_IN_INDEX), ',', -1)) AS incremental_row_per_key
  FROM
    INFORMATION_SCHEMA.INNODB_INDEX_STATS
    JOIN INFORMATION_SCHEMA.STATISTICS USING (TABLE_SCHEMA, TABLE_NAME, INDEX_NAME)
;
